### PR TITLE
GitLab support

### PR DESCRIPTION
**Pull request by justmara**
+ gitlab support
+ custom status' context property support
+ custom state string formatter to manage github/gitlab diferences on 'state' values

Were trying to keep copy-paste on minimal level and only implement differences between GitHub and GitLab. It resulted with some pretty ugly dance with beans config. I`m not a Java developer at all so maybe there is better way to do same things.

Tested on TeamCity 9.1.3 + GitLab 8.4.4 =)

### CODE REVIEW

**Comment by codez2love** [comment]
Any idea when this request will be merged to master? I'd be very great-full for this feature :)

**Comment by justmara** [comment]
@nd месяц висит без реакции. не нужен? 8) в трекере на тебе же [таск висит](https://youtrack.jetbrains.com/issue/TW-43079), видимо. тоже тишина.

**Comment by codez2love** [comment]
Yea i saw it's pretty quiet on their side :P. Anyway I've downloaded your fork, and I have added it to my TeamCity server. I can see it as external plugin in the Enabled Plugins list. But I don't see the build feature for notifying the build status(no additional feature was added to that list/dropdown :( ). Any idea what I'm doing wrong? Thanks!

**Comment by justmara** [comment]
@codez2love there must not be any new build feature but an option of 'Commit status publisher' list of publishers
teamcity-gitlab
Did you restarted your teamcity server? ;)
If you cant see 'Commit status publisher' feature at all - check the server log, there must be some initialization errors in teamcity-javaLogging-*.log during startup.

**Comment by codez2love** [comment]
@justmara That's exactly what i'm missing Commit status publisher in the Add Build Feature dropdown. I did try reset the teamcity server with no effects. 

teamcity-javaLogging-... -> http://pastebin.com/scTafaD2
dropdown

plugin

**Comment by justmara** [comment]
@codez2love then you have built it wrong =) use `mvn -B clean package` command in root of repo and get the zip from 'target' folder. Your one has even incorrect version shown - it must have value of 'snapshot-{timestamp}', so the maven action from `build/pom.xml` that changes version wasn't even fired.

**Comment by codez2love** [comment]
Yes, my bad. I forgot to actually package the code :D. I got it working now. Though it's missing GitLab option. And I downloaded the .zip from your repo :(.

missing

**Comment by codez2love** [comment]
Ah nevermind... It's on GitLab branch... I didn't notice... My bad again :D

**Comment by codez2love** [comment]
Ok one last question, what is the URL i should provide in case of GitLab cloud version? https://gitlab.com/api/v3 ? Or https://gitlab.com is enough? Also should the project be configured on GitLab side with Builds enabled or disabled. As far as I've noticed if Builds feature is enabled on GitLab side it will try to look for gitlab-ci.yml and build it with GitLab CI, so i guess they should be disabled.

**Comment by justmara** [comment]
@codez2love it has nnothing to do with gitlab builds. Commit status is a separate feature and can be ussed without GitLab inner CI.
gitlab-hlp
;)

**Comment by codez2love** [comment]
Thank you so much! I got it working :). I've been trying to get this working (without this plugin) for some days now without success.

**Comment by codez2love** [comment]
Hi again! :). I have another question :D. Does this plugin also support reporting the build status for merge-requests. My teamcity is configured to pull and build the merge-request. But the result does not get forwarded to gitlab. Do I have to do some extra configuration for this? Or is it not supported?
Thank you :)

**Comment by justmara** [comment]
@codez2love totally off topic;) But u cant `build merge-request`. Instead you build your repo at the slice of selected commit. And also there is no 'status' on merge request. Only comments ;)
So if you trigger build on a branch when merge-request created (via '/refs/heads/merge-requests/*') this plugin reports build status for the commit it was triggered for.

**Comment by neverov-test** [comment]
Hi @justmara,

sorry for delay. I'm not sure it is a good idea to reuse Github logic for Gitlab. These are totally different systems and there is no guarantee the common logic will work in future. 

I'd recommend implementing Gitlab support without reuse like it is done for bitbucket or stash. All constants used for Gitlab should be placed in Constants.java. Also could you please give an example when the context option might be useful? We removed it from github support, because the default value works for most of the cases. I'd start with the predefined value of the context and add an UI option if it's really needed.

**Comment by justmara** [comment]
@neverov-test 
GitLab and GitHub aren't `totally different systems`. Those are two web-interfaces for same underlying system (git). These interfaces totally rely on git subsystem so the can`t be really different in logic. They differ only in some interface parts - API URLs and constant names. That`s why I overloaded URL-resolving and implemented status-message resolving.

[Here is](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3365/builds) usage of context (Name column). The main idea is that u can run much more than one type of build for every commit ;) and you must get an easy way identify these builds on commit/merge pages.
There is predefined value and is only overloaded from ui. More than that - I've changed 'password' fields for auth token in favor of 'text' one, so you could use variables in it (it also required some template modifications also but I cant share it right now because I've already messed if with some other modifications we use locally).

**Comment by neverov-test** [comment]
> They differ only in some interface parts - API URLs and constant names.

Right, but commit-status-publisher only uses these interface parts, it doesn't use similar git back-end in any way. I think the implementation where Gitlab support shares no code with Github will be much easier to maintain, because both systems can change their API independently.

> The main idea is that u can run much more than one type of build for every commit ;) and you must get an easy way identify these builds on commit/merge pages.

Why not use a TeamCity build configuration name or build configuration external id (if context must be unique) for that?

**Comment by justmara** [comment]
> it doesn't use similar git back-end
it emulates part of this process by resolving latest version, getting branch names etc. This part is shared between GitHub and GitLab realizations 8) 
Theoretically - yes, they can change their APIs. But realistically those APIs realize similar logic for very similar products with only minimal cosmetic differences.

> Why not use a TeamCity build configuration name or build configuration external id (if context must be unique) for that?
Because there can be naming conventions for builds in TeamCity, and context - is informational text for quick info, not the id or anything else. Forcing it to use some build server property would be bad idea.

**Comment by neverov-test** [comment]
> Theoretically - yes, they can change their APIs.

'v3' in the API url suggests this is not just theoretical.

> Forcing it to use some build server property would be bad idea.

Why? I'm looking into the page you linked, it contains builds. A user has choosen a name for a build in TeamCity. How should he find it on the Gitlab page? It seems like it is natural to look for the build name, why the user should invent some context for Gitlab?

**Comment by justmara** [comment]
>  A user has choosen a name for a build in TeamCity. How should he find it on the Gitlab page? It seems like it is natural to look for the build name, why the user should invent some context for Gitlab?

Okay, now imagine this case:
TeamCity project administrator has chosen build name in TeamCity for his own ease of build management and his own naming scheme. Users of version control system must get readable messages about what exactly happened with their commits. These two 'names' are for different groups of readers, so they don`t have to match each other.
Also same build can be ran in different conditions for same commit on same branch (dev/qa/staging/production) with only difference in build parameters or tags...
There are tons of cases where commit status context cannot be automatically determined in plugin.

**Comment by neverov-test** [comment]
Following you logic an evil administrator can name a build configuration one way and specify a totally different context for Gitlab, just to confuse developers. People usually don't do that ;)

Speaking of readable messages, as a developer I'd expect to get a message like this:

> Build 'Project :: Release 2.5 :: Test DB' failed on commit XXX

If I get a Gitlab context instead of build name, then I will have to map build name to context and back over and over again.

Context might be useful, but I think it is easier to start with using a build name as a context.

**Comment by justmara** [comment]
Being a developer you're looking at the page of one particular commit and you dont really need its id in messages about actions it triggered. Also you dont need word 'build' for activities like static analysis, test run. These are named 'builds' only in realm of TeamCity.
We have non-developers commiting code and they must know that 'tests are green, syntax is green' and so on. PM wants to know that this merge-request was deployed, not that `Build' SomeProject :: Deployment :: master :: staging' has ran successfully`. He wants. `deploy:staging =green`. 
Stop thinking that all of this stuff is for developers. Forget the word 'build' and the wide new world will open itself for you ;)
So again. You can default it for whatever value you want. But it must be customizable.

**Comment by neverov-test** [comment]
>  These are named 'builds' only in realm of TeamCity.

Actually Gitab page you referenced has a *Builds* table and it has a *Name* column. I think even PM would expect to see a build name there ;)

But maybe you are right and this option can be customizable. My only concern is that once we make it available it is next to impossible to remove it. And if it is seldom used, then it is better to not add it.

**Comment by justmara** [comment]
My bad, that I've mixed two feature additions in same pr. 
Regarding shared code: there are two sides of this case. First: two separate systems that share same logic but different interface, and there really is possibility that this difference will grow up, making harder to support this shared code.
The other side- right now you want me to make total copy of project part and change two strings in it. Any fixes/updates in near future will require modification of two identical parts of code.
Imho the first threat is theoretical and delayed (and you'll refactor this code more than once before that time comes). The other threat is actual right now and in nearest feature.

**Comment by nd** [comment]
I've added GitLab support without common code with GitHub. It doesn't have the context field, the field can be added later if there will be a good reason for that. At this time people have to give a reasonable name to build configuration in TeamCity, which is a good practice anyway. Feel free to test it and provide feedback (plugin in master branch requires TeamCity-10). Happy building!

**Comment by carno** [comment]
@nd Any chance of having gitlab support merged into 9.1.x branch as well?

**Comment by nd** [comment]
@carno no, but you can install it on TeamCity 10 EAP

**Comment by carno** [comment]
I will not go with an EAP version in production env. Oh well, the good old curl will have to do the job.

**Comment by IlyaKhD** [comment]
Sorry, tldr.

Could you make it clear - is it possible to display TC build status on GitLab merge-request page (last commit built)?
Now it is 'CI build skipped' and I would like to know if it fails.

**Comment by justmara** [comment]
@carno you can catch it [here](https://teamcity.jetbrains.com/viewLog.html?buildId=758922&tab=artifacts&buildTypeId=TeamCityPluginsByJetBrains_CommitStatusPublisher_91)

**Comment by carno** [comment]
@justmara Thanks, I was able to build 9.x branch with merged support for gitlab, but still I faced an issue with merge requests (not really related to Teamcity or status publisher)
More info: https://youtrack.jetbrains.com/issue/TW-45099 & https://gitlab.com/gitlab-org/gitlab-ce/issues/15695

**Pull request closed without merging**
